/**
 * Compiles the Electron main process to V8 bytecode (LICENSING_SPEC §5).
 *
 * Two steps, and the order matters:
 *
 *  1. **Bundle.** The main process and everything it requires locally — the
 *     license verifier, the store, the gate — become one CommonJS file.
 *     Bytenode compiles a file, not a module graph, and rewriting every
 *     `require("./license/gate.cjs")` to point at a `.jsc` would be fragile.
 *     Node's builtins and the native/heavy packages stay external.
 *
 *  2. **Compile with Electron's own Node.** V8 bytecode is only loadable by
 *     the V8 that produced it. Compiling with the system Node would produce a
 *     file the shipped app cannot read, and the failure would appear at
 *     launch, on someone else's machine. So this script is run by Electron
 *     itself, and refuses to run otherwise.
 *
 * This raises the cost of reading the licensing logic. It does not make it
 * impossible — bytecode can be disassembled, and anyone determined enough will
 * get there. It is a lock on a door, not a vault.
 */
import { build } from "esbuild";
import { copyFileSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

const ROOT = process.cwd();
const OUT_DIR = join(ROOT, "electron", "build");
const BUNDLE = join(OUT_DIR, "main.bundle.cjs");
const BYTECODE = join(OUT_DIR, "main.jsc");
const LOADER = join(OUT_DIR, "main.cjs");

/** Packages that must stay external: native, huge, or resolved at runtime. */
const EXTERNAL = [
  "electron",
  "better-sqlite3",
  "node-llama-cpp",
  "next",
  "node-machine-id",
  "bytenode",
];

function assertRunningUnderElectron() {
  if (!process.versions.electron) {
    console.error(
      "compile-main must run under Electron, so the bytecode matches the V8\n" +
        "that will load it. Use:\n\n" +
        "  npm run electron:compile\n",
    );
    process.exit(1);
  }
}

async function main() {
  assertRunningUnderElectron();

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  await build({
    entryPoints: [join(ROOT, "electron", "main.cjs")],
    outfile: BUNDLE,
    bundle: true,
    platform: "node",
    format: "cjs",
    target: `node${process.versions.node.split(".")[0]}`,
    external: EXTERNAL,
    logLevel: "warning",
  });

  // The verifier reads its public key relative to __dirname, and __dirname
  // moves when the file is bundled — so the key travels with the bundle.
  copyFileSync(
    join(ROOT, "electron", "license", "license-public-key.pem"),
    join(OUT_DIR, "license-public-key.pem"),
  );

  // Same for the preload and the activation screen, which the bundled main
  // process loads by path.
  for (const asset of ["preload.cjs", "activation.html"]) {
    copyFileSync(join(ROOT, "electron", asset), join(OUT_DIR, asset));
  }

  const bytenode = require("bytenode");
  bytenode.compileFile({ filename: BUNDLE, output: BYTECODE });

  writeFileSync(
    LOADER,
    [
      "// Generated by scripts/compile-main.mjs — do not edit.",
      "// The main process ships as V8 bytecode; this is the two lines that load it.",
      'require("bytenode");',
      'require("./main.jsc");',
      "",
    ].join("\n"),
  );

  // The bundle is the readable source of the bytecode; shipping it alongside
  // would make the whole exercise pointless.
  rmSync(BUNDLE, { force: true });

  console.log(`Compiled main process -> ${BYTECODE.replace(ROOT, ".")}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
